version: '3.7'
services:
  mysql-mycrud:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-config/mysql/docker.cnf:/etc/docker.cnf