version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql-mycrud
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-config/mysql/docker.cnf:/etc/docker.cnf
  backend:
    image: node:15
    container_name: api-mycrud
    ports:
      - "8000:8000"
    working_dir: /application
    volumes:
      - ./docker-config/node/start_application.sh:/application/start_application.sh
      - ./backend:/application/app/
    entrypoint: ["/application/start_application.sh"]
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/users"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    image: nginx:1.20.2
    container_name: nginx-mycrud
    ports:
      - "80:80"
    volumes:
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5